### ISSUE TITLE
Add ability to hide the Subscribe/unsubscribe/mark as read

### ISSUE THREAD

**Issue by pab74** [DigitalFlow/D365-PowerKanban#10]
If the configuration doesnt contain the lookups for the notification/subscription the dropdown button should be hidden maybe. Or add a property "Show Subscription":true/false

**Comment by DigitalFlow** [comment]
Hi @pab74,

Please check, on my side the controls are hidden if the configuration does not include the notificationLookup and subscriptionLookup settings.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
This is how it looks at my side with v0.9.7:

![image](https://user-images.githubusercontent.com/4287938/88813336-159d3280-d1b9-11ea-8fd9-4e44bdfc6cf4.png)

Config:
```JSON
asdf
```

**Comment by pab74** [comment]
You are right, after cleaning the cache it worked.
