### ISSUE TITLE
Button is visible in the form.

### ISSUE THREAD

**Issue by molyom** [DigitalFlow/D365-PowerKanban#12]
![image](https://user-images.githubusercontent.com/12083302/88904653-a1649c80-d255-11ea-9d97-8efb0888a020.png)

**Comment by molyom** [comment]
![image](https://user-images.githubusercontent.com/12083302/88904782-d1ac3b00-d255-11ea-951a-ade881ec5577.png)

**Comment by DigitalFlow** [comment]
Fixed in v0.9.8, please install and test.
If not solved, please reopen again.
