### ISSUE TITLE
After update record in Modal o split window, it remain in the same state. don't refresh the view. 

### ISSUE THREAD

**Issue by molyom** [DigitalFlow/D365-PowerKanban#14]
![image](https://user-images.githubusercontent.com/12083302/88918258-75531680-d269-11ea-9776-a135c9437c0b.png)

This button does`t work for update the view after change data in record. and also there is no other Refresh button to do that. You have to go out and back to open the control to refresh the view again.

**Comment by molyom** [comment]
If I change the view and back to that same view (My Open Projects)  it refreshes.

**Comment by DigitalFlow** [comment]
Hi @molyom,

there should be a refresh button inside the PCF at the very right, as you can see here:
https://user-images.githubusercontent.com/4287938/85366990-adf42780-b528-11ea-8848-bc035b21ae4f.png

But in any case, clicking on the refresh button should refresh as well. It already does so when you add new data or remove data, but refreshing when data was only updated should indeed work as well.

**Comment by molyom** [comment]
Thanks @DigitalFlow , I found it. It works as well. But as you told, auto refresh after update data will be good! 👍

**Comment by DigitalFlow** [comment]
Fixed in v0.9.8, please install and test.
If not solved, please reopen again.
