### ISSUE TITLE
 "allowTransitions": false: Does Not work

### ISSUE THREAD

**Issue by molyom** [DigitalFlow/D365-PowerKanban#16]
{
    "primaryEntity": {
        "allowTransitions": **false**,
        "logicalName": "opportunity",
        "swimLaneSource": "pes_projectstatus",  
....

I can move the state and it doesn't block me.

**Comment by molyom** [comment]
I also deleted all of the line like below: 

"primaryEntity": {
"logicalName": "opportunity",
"swimLaneSource": "pes_projectstatus",

and as you describe it, it has to be disabled by default and evoid changes. But I can move it form one state to other.

**Comment by DigitalFlow** [comment]
Fixed in v0.9.8, please install and test.
If not solved, please reopen again.

**Comment by DigitalFlow** [comment]
Please also note, that this is no longer called `allowTransitions` but `preventTransitions`.
I think it feels more natural like this, as you most often will not block it and can thus leave this option out.
