### ISSUE TITLE
Default view option

### ISSUE THREAD

**Issue by rhanoudi** [DigitalFlow/D365-PowerKanban#17]
After using the default Kanban control that ships with D365, we noticed many limitations.  Excellent job and thank you for doing this work.

I enable PowerKanban on the opportunity entity and specifically set it for the "All Opportunities" view.  When I go to the view, it defaults to "My Opportunities".  Did I miss a configuration setting to set the default view?

**Comment by DigitalFlow** [comment]
Hi @rhanoudi,

I'm glad that you like it :+1:

The default view is currently in progress of being developed, it first appeared in #7 and I will probably implement it today or this weekend.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Fixed in v0.9.8, please install and test.
If not solved, please reopen again.

**Comment by ram-sannidi** [comment]
i am also facing the same issue. Default view id which is mentioned in config is not set.
