### ISSUE TITLE
unable to use xrm-webapi-client

### ISSUE THREAD

**Issue by RamNemely** [DigitalFlow/D365-PowerKanban#2]
Hi,

Thanks for such wonderful component.

I am trying to use xrm-webapi-client same as is used in this. But when i installed and tried to use methods, intellisense is not showing any available methods. Could you please help me what i am missing here.

Thanks
Ram

**Comment by DigitalFlow** [comment]
Hi @RamNemely,

thanks for giving it a spin 👍 

Yes, unfortunately the PCF framework does not like default exports as how it is done in Xrm-WebApi-Client.
I had overridden it locally in my node_modules folder for the time being, which is of course not great.

I just published a new version of Xrm-WebApi-Client (v4.0.0) to npm, which incorporates my fix for PCF usage.
Can you give it a spin, whether it works now?

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Closing this, as it should be fixed.
If you still have issues, please open an issue on the xrm-webapi-client repo.

**Comment by RamNemely** [comment]
Hi,

I have used some other API and did not get a chance to try this. Sure will
try and open a ticket as suggested if any issues.

Thanks
Ram
