### ISSUE TITLE
Every time that you change form Advance to Simple, the second entity button remains in the top.

### ISSUE THREAD

**Issue by molyom** [DigitalFlow/D365-PowerKanban#23]
![image](https://user-images.githubusercontent.com/12083302/90653414-6eec0500-e23f-11ea-9ea6-fe1c72e42edf.png)

**Comment by DigitalFlow** [comment]
Hi @molyom,

please try v0.9.12, should be fixed there.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @molyom,

I'll close this issue, if the issue is not fixed for you in the latest version, please reopen.

Kind Regards,
Florian

**Comment by molyom** [comment]
Fiexd. Thanks
