### ISSUE TITLE
Kanban error on Subscription lookup

### ISSUE THREAD

**Issue by MitchMilam** [DigitalFlow/D365-PowerKanban#4]
I have tried omitting the subscriptionlookup and notificationlookup properties from the config but get this error: cannot read property 'subscriptionlookup' of undefined.

Trying to add this to the Lead entity.

Any pointers?

Thanks, Mitch

**Comment by DigitalFlow** [comment]
Hi @MitchMilam,

Thanks for giving it a spin.
I noticed this too, can you try whether this is fixed for you in v0.9.2 which I just published?

Kind Regards,
Florian

**Comment by MitchMilam** [comment]
0.9.3 solved that problem. Thanks
