### ISSUE TITLE
Customer created campaign card not appearing on Board

### ISSUE THREAD

**Issue by JladanZA** [DigitalFlow/D365-PowerKanban#5]
Hi 

I've tried to setup Power Kanban on the Campaign entity, with tasks as secondary.
I received an error that the campaign entity did not have a card form, which I have now created. 

The board now loads, and I can see a count of campaigns, however none of the cards load. The secondary cards using the advanced view do load.

I've double checked the card and it seems to be fine, so not too sure what I am doing wrong?
![No Campaign Card](https://user-images.githubusercontent.com/28859964/88374293-cf4f6a00-cd99-11ea-80a1-55939258bf53.PNG)
![Tasks linked to campaign](https://user-images.githubusercontent.com/28859964/88374298-d1192d80-cd99-11ea-8e82-8b71083b5307.PNG)

Images attached.

**Comment by DigitalFlow** [comment]
Hi @JladanZA,

thanks for giving this solution a spin :grin:

In which status is the campaign which is not showing in the simple view?
Is the lane of its status rendered without any data in it?

Kind Regards,
Florian

**Comment by JladanZA** [comment]
It is in the proposed status. Interestingly I've just tested now, when changed to the ready to launch status, then the card shows up, by then the advanced view breaks

**Comment by JladanZA** [comment]
Further info, I can drag the campaign card into ready, launched and completed. When dragging into proposed it refuses. When dragging into cancelled it dissapears. I'm wondering if I have views that are excluding those records

**Comment by DigitalFlow** [comment]
Hi @JladanZA,

thanks for the update.
I'll try to reproduce your issue, can you please send me the configuration which you created for this board?

Kind Regards,
Florian

**Comment by JladanZA** [comment]
{
    "primaryEntity": {
        "allowTransitions": true,
        "logicalName": "campaign",
        "swimLaneSource": "statuscode",
        "notificationLookup": "campaignid",
        "subscriptionLookup": "campaignid",
        "transitionCallback": "boardViewExtender.onStateTransition"
    },
    "defaultViewId": "",
    "showCreateButton": true,
    "showDeleteButton": true,
    "showDeactivateButton": true,
    "secondaryEntity": {
        "allowTransitions": true,
        "logicalName": "task",
        "notificationLookup": "activityid",
        "parentLookup": "regardingobjectid",
        "subscriptionLookup": "activityid",
        "swimLaneSource": "statuscode"
    },
    "customScriptUrl": "/WebResources/oss_/D365BoardView/js/exampleExternalScript.js"
}

**Comment by DigitalFlow** [comment]
@JladanZA 
Ok I guess I found the error, can you please remove the "customScriptUrl" from your config and the "transitionCallBack" inside your primary entity?
This might interfere, this is only for the CRM case example.

Do the issues still persist afterwards? And was there any error shown when the advanced view crashed?

**Comment by JladanZA** [comment]
Revised to below, issue still persists

{
    "primaryEntity": {
        "allowTransitions": true,
        "logicalName": "campaign",
        "swimLaneSource": "statuscode",
        "notificationLookup": "campaignid",
        "subscriptionLookup": "campaignid"
        
    },
    "defaultViewId": "",
    "showCreateButton": true,
    "showDeleteButton": true,
    "showDeactivateButton": true,
    "secondaryEntity": {
        "allowTransitions": true,
        "logicalName": "task",
        "notificationLookup": "activityid",
        "parentLookup": "regardingobjectid",
        "subscriptionLookup": "activityid",
        "swimLaneSource": "statuscode"
		
    }

}

**Comment by DigitalFlow** [comment]
@JladanZA :

My last post edit might have got lost, can you please also remove the notificationLookup and subscriptionLookup values in both primary and secondary entity?
These fields need to be created manually right now, the values which I see there currently are definetly not correct.

Can you try whether it works without them?

**Comment by JladanZA** [comment]
Current config error remains

{
    "primaryEntity": {
        "allowTransitions": true,
        "logicalName": "campaign",
        "swimLaneSource": "statuscode"
        
        
    },
    "defaultViewId": "",
    "showCreateButton": true,
    "showDeleteButton": true,
    "showDeactivateButton": true,
    "secondaryEntity": {
        "allowTransitions": true,
        "logicalName": "task",
        "parentLookup": "regardingobjectid",
        "swimLaneSource": "statuscode"
		
    }
    
}

**Comment by DigitalFlow** [comment]
Ok,

In that case I'll really have to set it up on my side as well.
Can you post your status reason values of the campaign, each with their value and the corresponding label?
In case you see any errors when you press F12 in your browser, the messages would be very helpful.

**Comment by JladanZA** [comment]
im using it exactly as it is out of the box. no changes made, the only other thing i did is create the card form for campaign as campaign does not have a card form by default

![campaign card form](https://user-images.githubusercontent.com/28859964/88382594-0ed18280-cda9-11ea-8549-0bdccfbb418c.PNG)

**Comment by DigitalFlow** [comment]
@JladanZA:
Found the issue, expect a fix very soon, probably today.

**Comment by JladanZA** [comment]
great stuff thanks

**Comment by DigitalFlow** [comment]
Please upgrade to v0.9.3: https://github.com/DigitalFlow/D365-PowerKanban/releases/tag/v0.9.3

This should fix the issues you were experiencing.
Hint: If you want to be notified per email once new versions arrive, you can toggle the "Watch" button on the top of this webpage.

**Comment by JladanZA** [comment]
That seems to have resolved the issue. Thanks! Will continue testing

**Comment by DigitalFlow** [comment]
Allright, thanks for reporting :+1:
I'll close this issue, please open a new issue for each new issue you might find.
I hope everything to be quite stable however. The connection to the dynamics default buttons at the top of the control are not yet completely done, this is still work in progress.

I hope to release a proper usage and configuration documentation soon.

**Comment by JladanZA** [comment]
It certainly looks very promising and useful piece of kit

**Comment by DigitalFlow** [comment]
Thanks a lot.
There's quite a lot of functionality to be discovered, but it's hard to find everything as long as the documentation is not done.
I expect the subscription and notification feature that is built in to be very useful as well, but getting started needs to become easier. 
In the future creating configurations will probably be assisted, so that it's easier and better explained.
