### ISSUE TITLE
Ready for UCI

### ISSUE THREAD

**Issue by MitchMilam** [DigitalFlow/D365-PowerKanban#6]
I noticed that at least the Config entity does not have the checkbox checked for Enable for Unified Client.

That setting probably needs to be set for all entities in the solution.

**Comment by DigitalFlow** [comment]
Hi @MitchMilam,

Thanks for pointing out, you're right, the checkbox is missing for every custom entity in the solution.
I just toggled the setting for all of them.

I hope to release v0.9.4 at some point this weekend, changes will be included then.

PS: If you test further and stumble across the Dynamics toolbar not interacting properly with the control, for example grid does not refresh after creating a new record using the default button, or not being able to select records for triggering buttons, this is WIP.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @MitchMilam,

just released an updated solution (v0.9.4) where among other changes, these flags are now checked.

Kind Regards,
Florian
