### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by surfmaverick** [DigitalFlow/D365-PowerKanban#7]
Is there a guide to the configuration settings?

Also, how do I determine the Id of the view I would like to default o?

**Comment by DigitalFlow** [comment]
Hi @surfmaverick,

I just extended the Config Section in the ReadMe: https://github.com/DigitalFlow/D365-PowerKanban#basic-config
In addition to that, I added a JSON Schema description: https://github.com/DigitalFlow/D365-PowerKanban#configuration

Does that help you? I hope to simplify configuration in the future by providing a PCF inside the powerkanban config entity which assists in creating the JSON, but this is not yet done.

Kind Regards,
Florian

**Comment by surfmaverick** [comment]
Yes, thanks.

On Jul 29, 2020, at 12:02 AM, Florian Krönert <notifications@github.com> wrote:


Hi @surfmaverick <https://github.com/surfmaverick>,

I just extended the Config Section in the ReadMe: https://github.com/DigitalFlow/D365-PowerKanban#basic-config <https://github.com/DigitalFlow/D365-PowerKanban#basic-config>
In addition to that, I added a JSON Schema description: https://github.com/DigitalFlow/D365-PowerKanban#configuration <https://github.com/DigitalFlow/D365-PowerKanban#configuration>
Does that help you? I hope to simplify configuration in the future by providing a PCF inside the powerkanban config entity which assists in creating the JSON, but this is not yet done.

Kind Regards,
Florian

**Comment by surfmaverick** [comment]
How do I change the default view?



It’s defaulting to the first on the list, which is not the one I would like.  I would like it to open to “My Open Tasks”.

Chris

On Jul 29, 2020, at 12:02 AM, Florian Krönert <notifications@github.com> wrote:


Hi @surfmaverick <https://github.com/surfmaverick>,

I just extended the Config Section in the ReadMe: https://github.com/DigitalFlow/D365-PowerKanban#basic-config <https://github.com/DigitalFlow/D365-PowerKanban#basic-config>
In addition to that, I added a JSON Schema description: https://github.com/DigitalFlow/D365-PowerKanban#configuration <https://github.com/DigitalFlow/D365-PowerKanban#configuration>
Does that help you? I hope to simplify configuration in the future by providing a PCF inside the powerkanban config entity which assists in creating the JSON, but this is not yet done.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @surfmaverick,

This is not yet implemented yet.
I added it to my to do list and I think it will be done pretty soon.
There will be a new property "defaultViewId" for the primary entity as well as for the secondary entity, so that you can configure it there.

Kind Regards,
Florian

**Comment by surfmaverick** [comment]
Cool, thanks.  That works great.

On Jul 29, 2020, at 12:17 AM, Florian Krönert <notifications@github.com> wrote:


Hi @surfmaverick <https://github.com/surfmaverick>,

This is not yet implemented yet.
I added it to my to do list and I think it will be done pretty soon.
There will be a new property "defaultViewId" for the primary entity as well as for the secondary entity, so that you can configure it there.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Fixed in v0.9.8, please install and test.
If not solved, please reopen again.

**Comment by surfmaverick** [comment]
Is this posted to git?

On Aug 2, 2020, at 4:28 PM, Florian Krönert <notifications@github.com> wrote:


Fixed in v0.9.8, please install and test.
If not solved, please reopen again.

**Comment by DigitalFlow** [comment]
Yes, it's commit f9eff1d on master
