### ISSUE TITLE
Regarding link on task card pointing to a custom entity doesn't open the record

### ISSUE THREAD

**Issue by pab74** [DigitalFlow/D365-PowerKanban#8]
Hello Florian,
great piece of code. I just noticed that if the Regarding field on my task card points to e.g. the Account entity or Contact entity, it works. If I click the link pointing to a custom entity, nothing happens.
https://www.loom.com/share/ff2dbe6b308a42008b4a4fe27ce0f0c2
Cheers
Paolo

**Comment by DigitalFlow** [comment]
Hi @pab74,

thanks for reporting (and for the helpful video).
Can you please press the F12 button and check whether there are any errors logged after clicking the lookup?
To me it seems it flickers for short when you click, so something might be failing.

Kind Regards,
Florian

**Comment by pab74** [comment]
Hello Florian,
unfortunately it seems non errors are logged.
Paolo

**Comment by DigitalFlow** [comment]
Hi @pab74,

The bug is identified, expect a fix very soon 👍 

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @pab74,

I fixed this in v0.9.7, can you give it a try?

Kind Regards,
Florian

**Comment by pab74** [comment]
Yeah! It works
